In [4]:
import keras
from keras.layers import Dense
from keras.models import Sequential
import numpy as np
# Dataset Link : # https://archive.ics.uci.edu/ml/datasets/Blood+Transfusion+Service+Center
# Save the dataset as a .csv file :
tran_ = np.genfromtxt('transfusion.data', delimiter=',')
X=tran_[:,0:4] # The dataset offers 4 input variables
Y=tran_[:,4] # Target variable with '1' and '0'
print(X)

[[     nan      nan      nan      nan]
 [2.00e+00 5.00e+01 1.25e+04 9.80e+01]
 [0.00e+00 1.30e+01 3.25e+03 2.80e+01]
 ...
 [2.30e+01 3.00e+00 7.50e+02 6.20e+01]
 [3.90e+01 1.00e+00 2.50e+02 3.90e+01]
 [7.20e+01 1.00e+00 2.50e+02 7.20e+01]]


In [7]:
mlp_keras = Sequential()
mlp_keras.add(Dense(8, input_dim=4, activation='relu'))
mlp_keras.add(Dense(6,  activation='relu'))
mlp_keras.add(Dense(1,  activation='sigmoid'))

In [11]:
mlp_keras.compile(loss = 'binary_crossentropy', optimizer='adam',metrics=['accuracy'])
mlp_keras.fit(X,Y, epochs=200, batch_size=8, verbose=0)

In [12]:
accuracy = mlp_keras.evaluate(X,Y)
print("Accuracy : %.2f%% " % (accuracy[1]*100 ))

24/24 [==============================] - 0s 1ms/step - loss: nan - accuracy: 0.7610
Accuracy : 76.10% 


In [13]:
from keras.optimizers import SGD
opt = SGD(lr=0.01)
mlp_optim = Sequential()
mlp_optim.add(Dense(8, input_dim=4, activation='relu'))
mlp_optim.add(Dense(6,  activation='relu'))
mlp_optim.add(Dense(1, activation='sigmoid'))

In [14]:
mlp_optim.compile(loss = 'binary_crossentropy', optimizer=opt, metrics=['accuracy'])
# Fitting the model and checking accuracy
mlp_optim.fit(X,Y, validation_split=0.3, epochs=150, batch_size=10, verbose=0)
results_optim = mlp_optim.evaluate(X,Y)
print("Accuracy : %.2f%%" % (results_optim[1]*100 ) )

24/24 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.7610
Accuracy : 76.10%
