In [2]:
import tensorflow as tf
hello = tf.constant('Hello, Tensors!')
tf.print(hello)

Hello, Tensors!


In [4]:
a = tf.constant(10)
b = tf.constant(32)
tf.print(a+b)

42


In [5]:
import tensorflow as tf
import numpy as np
mat_1 = 10*np.random.random_sample((3, 4)) # Creating NumPy
mat_2 = 10*np.random.random_sample((4, 6))
# Creating a pair of constant ops, and including the above made
tf_mat_1 = tf.constant(mat_1)
tf_mat_2 = tf.constant(mat_2)
# Multiplying TensorFlow matrices with matrix multiplication
tf_mat_prod = tf.matmul(tf_mat_1 , tf_mat_2)
tf.print(tf_mat_prod)

[[43.790774372447913 140.7654981178857 93.602424799223314 121.04294213644954 122.38667012430646 179.88047333760449]
 [70.988633946811618 142.5131597554554 82.9954743166706 147.86939609101162 108.22343038233214 159.24298622127881]
 [66.202636346975737 121.39964520887776 65.127283021909 134.61501912416256 99.074410889339774 146.42846683130298]]


In [6]:
a = tf.constant(10)
b = tf.constant(20)
tf.print(a+b)

30


In [7]:
tf.print(a-b)

-10
