# Numpy

In [1]:

import numpy as np


In [3]:
x=np.random.rand(10)
print('ndim',x.ndim)
print('dtype',x.dtype)

ndim 1
dtype float64


In [4]:
a=np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11]])
rows,cols=np.shape(a)
print('n items', a.itemsize)

n items 4


# Numero Complejos

In [11]:
b=np.array([[2,3],[6,7]],dtype=np.complex64)
print(type(b))
print(b.dtype)


<class 'numpy.ndarray'>
complex64


In [12]:
v=np.zeros((4,5))
print(v)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [13]:
e=np.eye(5)
print(e)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [15]:
ze=np.zeros_like(b)
print(ze)

[[0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j]]


In [18]:
a=np.arange(2,7)
print(a)
di=np.diag(a)
print(di)

[2 3 4 5 6]
[[2 0 0 0 0]
 [0 3 0 0 0]
 [0 0 4 0 0]
 [0 0 0 5 0]
 [0 0 0 0 6]]


In [20]:
r=np.arange(10)
x=r.reshape(2,5)
print(x)

[[0 1 2 3 4]
 [5 6 7 8 9]]


$ Podemos generar matrices mas complejas $

In [24]:
d=np.linspace(0,12,5)
print(d)
dP=d[np.newaxis,:]
print(dP)
dH=d[:,np.newaxis]
print(dH)

[ 0.  3.  6.  9. 12.]
[[ 0.  3.  6.  9. 12.]]
[[ 0.]
 [ 3.]
 [ 6.]
 [ 9.]
 [12.]]


## Scipy

In [33]:
from scipy import sparse
X=np.random.random((5,6))
print(X)
X[X<0.85]=0
print(X)
x_csr=sparse.csr_matrix(X)
print(x_csr)

[[0.87810313 0.63952891 0.94869898 0.86375625 0.71431857 0.87972588]
 [0.06992623 0.73122342 0.34420929 0.11486153 0.37101332 0.43695783]
 [0.87518962 0.56784178 0.74150199 0.28460741 0.49112503 0.56537565]
 [0.18640111 0.16234648 0.8438549  0.94373175 0.38062898 0.12949634]
 [0.09634825 0.28734383 0.15591857 0.39412881 0.04643899 0.18891614]]
[[0.87810313 0.         0.94869898 0.86375625 0.         0.87972588]
 [0.         0.         0.         0.         0.         0.        ]
 [0.87518962 0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.94373175 0.         0.        ]
 [0.         0.         0.         0.         0.         0.        ]]
  (0, 0)	0.8781031279831452
  (0, 2)	0.9486989838686678
  (0, 3)	0.8637562503473998
  (0, 5)	0.879725884088441
  (2, 0)	0.8751896174550308
  (3, 3)	0.9437317483441306


In [34]:
from scipy import linalg
arr = np.array([[1,2],[3,4]])
print(linalg.det(arr))

-2.0


In [40]:
np.random.seed(12345)
rn=np.random.rand(4)
print(rn)


[0.92961609 0.31637555 0.18391881 0.20456028]
